ARG ELASTIC_VERSION
FROM logstash:${ELASTIC_VERSION}

# MySQL Connector/J JAR 파일을 이미지에 복사
# COPY /usr/share/java/mysql-connector-java-8.1.0.jar /usr/share/logstash/logstash-core/lib/jars/mysql-connector-java-8.1.0.jar
